---
- 
 hosts: localhost
 connection: local
 gather_facts: false
 vars:
    tower_api_url: "https://10.42.0.42"
    tower_token: "KTk9rN2osEhAi3FF9dvvdFpXi4l4ai"
    job_id: 180

 tasks:
   - name: Check that tower job has finished
     uri:
       url: "{{ tower_api_url }}/api/v2/jobs/{{ job_id }}/"
       method: GET
       validate_certs: no
       status_code: 201, 200
       headers:
         Content-Type: application/json
         Authorization: "Bearer {{ tower_token }}"
     register: job_result
     ignore_errors: true
   
   - name: print the result
     ansible.builtin.debug:
       msg: "{{ job_result['json']['related'] }}"
   
