---
- 
 hosts: localhost
 connection: local
 gather_facts: false
 vars:
    tower_api_url: "https://10.42.0.42"
    tower_token: "KTk9rN2osEhAi3FF9dvvdFpXi4l4ai"
    job_id: "{{awx_job_id - 1}}"

 tasks:
   - name: Check that tower job has finished
     uri:
       url: "{{ tower_api_url }}/api/v2/jobs/{{ job_id }}/"
       method: GET
       validate_certs: no
       status_code: 201, 200
       headers:
         Content-Type: application/json
         Authorization: "Bearer {{ tower_token }}"
     register: job_result
     ignore_errors: true
   
   - name: print the result
     vars:
       TemplateName: "{{ job_result['json']['summary_fields']['job_template']['name'] }}"
       organization: "{{ job_result['json']['summary_fields']['organization']['name'] }}" 
       Jobstatus: "{{ job_result['json']['status']}}" 
         
     ansible.builtin.debug:
       msg: 
       - "TemplateName: {{ TemplateName }}"
       - "Org: {{ organization}}"
       - "JobStatus: {{Jobstatus}}"
   
