---
- 
 hosts: all
 gather_facts: true
 vars:
    tower_api_url: "https://10.42.0.42"
    tower_token: "KTk9rN2osEhAi3FF9dvvdFpXi4l4ai"
            
 tasks:
   - name: Example from an Ansible Playbook
     win_ping:
     register : results
     
   - name: Display all cluster names
     ansible.builtin.debug:
       var: item
     loop: "{{ results | json_query("[*]") }}"
