---
- 
 hosts: all
 gather_facts: false
 tasks:
   - name: Example from an Ansible Playbook
     win_ping:
     register : results
     
   - name: Print return information from the previous task
     ansible.builtin.debug:
       var: results
       verbosity: 4

   - name: Check that tower job has finished
       uri:
         url: "{{ tower_api_url }}/api/v2/jobs/{{ job_id }}/"
         method: GET
         validate_certs: no
         status_code: 201, 200
         headers:
           Content-Type: application/json
           Authorization: "Bearer {{ tower_token }}"
       register: job_result
       ignore_errors: true

   - name: print job_result
       debug:
         msg: "{{ job_result['summary_fields'] }}"
