---
- 
 hosts: all
 gather_facts: true
           
 tasks:
   - name: Example from an Ansible Playbook
     win_ping:
     register : results

   - name: Display values
     vars:
       Servername: "{{ansible_host}}"
       Status: "{{ (results |to_yaml| list) }}"
     ansible.builtin.debug:
       msg: "{{Servername}} : {{Status}}"
