---
- 
 hosts: all
 tasks:
   - name: Example from an Ansible Playbook
     win_ping:
     register : results
     
   - name: Print return information from the previous task
     ansible.builtin.debug:
       var: results
       verbosity: 2
 
