---
- 
 hosts: all
 gather_facts: true
           
 tasks:
   - name: Example from an Ansible Playbook
     win_ping:
     register : results

   - name: Display values
     vars:
       Servername: "{{ansible_host}}"
       Status: "{{ (results['ping']) }}"
     ansible.builtin.debug:
       msg: "{{Servername}} : {{Status}}"
   - name: test list comparisions.
     set_fact:
       listone: [1,2,3]
       listtwo: 2
   - debug:
       msg:
        - "{{ listone }}"
        - "{{ listtwo }}"
        - "{{ listone|string| reject('equalto', '2') | list }}"
       
